spring:
  application:
    name: learning-platform

  datasource:
    url: jdbc:postgresql://dpg-dagfvj942hec73c5qnng-a:5432/postgres_8kub
    username: postgres_8kub_user
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration

  jackson:
    serialization:
      write-dates-as-timestamps: false

  thymeleaf:
    cache: ${THYMELEAF_CACHE:false}
    check-template-location: true
    enabled: true
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  address: 0.0.0.0
  port: ${PORT:8081}
